### PR TITLE
Polyfill for casper-storage

### PR DESCRIPTION
**Pull request by codsay**
### Summary (Please recap what you changed or fixed)

Polyfill for casper-storage

### Checklist (If you won't pass this checklist please comment why)

-   [x] I removed all commented or unnecessary code.
-   [x] Provide the screenshots due to UI changed or bug fixed
-   [x] My code has covered these test cases (please list down your tested cases):

### CODE REVIEW

**Comment by codsay** [comment]
> 

@ThanhNguyen140797 did you run on ios or android? android, right?

**Comment by codsay** [comment]
@ThanhNguyen140797 can you try again? I reverted back the polyfill for BigInt

**Comment by ThanhNguyen140797** [comment]
> @ThanhNguyen140797 can you try again? I reverted back the polyfill for BigInt

Look good. Now i got this issue when create new User.
**[TypeError: Expected valid scalar: 0 < scalar < max]**
Screen Shot 2022-04-21 at 07 25 00

My code: 
`
       const user = new User(pin, {
          passwordOptions: { passwordValidator: () => new ValidationResult(true) },
      });

      user.setHDWallet(phrases, EncryptionType.Ed25519);
      const acc0: IWallet<IHDKey> = await user.getWalletAccount(0);
      user.setWalletInfo(
        acc0.getReferenceKey(),
        new WalletDescriptor('Account 1'),
      );
      const publicKey = await acc0.getPublicAddress();
      const hashingOptions = user.getPasswordHashingOptions();
`
Hi @djhahe please check this issue.

**Comment by codsay** [comment]
@ThanhNguyen140797 can you please share me your running env? node + ios version.

I tried to clean up everything and started from scratch but it worked fine for me
image

**Review by djhahe — APPROVED** [review]
LG, I can create and add wallet without issue.

**Pull request merged**
