### PR TITLE
Update README to run the project

### PR DESCRIPTION
**Pull request by gaupoit**
### Summary (Please recap what you changed or fixed)

- Update README to build and run the project on Android and iOS

### Checklist (If you won't pass this checklist please comment why)

-   [x] I removed all commented or unnecessary code.
-   [x] Provide the screenshots due to UI changed or bug fixed
-   [x] My code has covered these test cases (please list down your tested cases): 

- Run on iOS
- Run on Android

### CODE REVIEW

**Review by djhahe — COMMENTED** [review]
Please add instruction about env config, and explain about the architecture as detail as possible

**Comment by gaupoit** [comment]
hi @djhahe @ThanhNguyen140797 , please help me to double check it again. Thanks.

**Comment by ThanhNguyen140797** [comment]
Run android might caught this issue.

`> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
`

Sometimes, configure the ANDROID_HOME environment variables are not enough.
Resolve:

1. Go to your React-native Project -> Android
2. Create a file local.properties
2. Open the file paste your Android SDK path like below: 
in Windows: sdk.dir = C:\\Users\\USERNAME\\AppData\\Local\\Android\\sdk
in macOS: sdk.dir = /Users/USERNAME/Library/Android/sdk
in linux: sdk.dir = /home/USERNAME/Android/Sdk

Replace USERNAME with your user name.

@gaupoit Please add this guide.

**Comment by gaupoit** [comment]
> Run android might caught this issue.
> 
> `> SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable. `
> 
> Sometimes, configure the ANDROID_HOME environment variables are not enough. Resolve:
> 
> 1. Go to your React-native Project -> Android
> 2. Create a file local.properties
> 3. Open the file paste your Android SDK path like below:
>    in Windows: sdk.dir = C:\Users\USERNAME\AppData\Local\Android\sdk
>    in macOS: sdk.dir = /Users/USERNAME/Library/Android/sdk
>    in linux: sdk.dir = /home/USERNAME/Android/Sdk
> 
> Replace USERNAME with your user name.
> 
> @gaupoit Please add this guide.

I updated in this commit: https://github.com/CasperDash/casperdash-mobile-wallet/pull/19/commits/6d2a64397ac46bf11c4d4a0a23ee713f8c29a26e

**Comment by djhahe** [comment]
Lgtm

**Review by djhahe — APPROVED** [review]

**Review by ThanhNguyen140797 — APPROVED** [review]

**Pull request merged**
