### PR TITLE
Feature/Splash-screen

### PR DESCRIPTION
**Pull request by ThanhNguyen140797**
### Summary 
Done Splash screen
### Checklist

-   [x] I removed all commented or unnecessary code.
-   [x] Provide the screenshots due to UI changed or bug fixed

### CODE REVIEW

**Comment by gaupoit** [comment]
simulator_screenshot_08A44859-91D9-42ED-A92B-72A0C79B030B

hi @ThanhNguyen140797, please resolve this warning. Thanks bro.

**Comment by ThanhNguyen140797** [comment]
> simulator_screenshot_08A44859-91D9-42ED-A92B-72A0C79B030B
> 
> hi @ThanhNguyen140797, please resolve this warning. Thanks bro.

Does this app use Code Push? If it does, please provide CodePushDeploymentKey for iOS and Android

**Comment by gaupoit** [comment]
hi @ThanhNguyen140797 , could you please to support swipe (left/right) action on the splash screens? Thanks.

**Comment by ThanhNguyen140797** [comment]
Reopen

**Review by gaupoit — APPROVED** [review]
LGTM

**Pull request merged**
