### PR TITLE
Feature/support 24 words recovery phrase

### PR DESCRIPTION
**Pull request by djhahe**
### Summary (Please recap what you changed or fixed)

image

### Checklist (If you won't pass this checklist please comment why)

-   [x] I removed all commented or unnecessary code.
-   [x] Provide the screenshots due to UI changed or bug fixed
-   [ ] My code has covered these test cases (please list down your tested cases):

### CODE REVIEW

**Comment by duc-q** [comment]
@djhahe 

IMO it would be more understanding when we can be clear on the label. 

We can try something like:
```
Phrase length: [12 words] [24 words]
```

Cheers,

**Comment by djhahe** [comment]
@duc-q 
There're many texts on this screen so I dont want to add more texts there. And 12 is match with 12 words bellow so I think it clear enough to user.

**Comment by gaupoit** [comment]
> @djhahe
> 
> IMO it would be more understanding when we can be clear on the label.
> 
> We can try something like:
> 
> ```
> Phrase length: [12 words] [24 words]
> ```
> 
> Cheers,

Agreed. Also need to explain why they need to choose 12 or 24. And which one is better?

**Comment by gaupoit** [comment]
We will improve this UI later. I will merge it for testing purpose

**Review by gaupoit — APPROVED** [review]

**Pull request merged**
